siteMetadata:
  name: My Blog
  title: Gatsby Blog Starter
  author: n8tb1t
  description: Simple yet powerful blog solution.
  siteUrl: http://localhost:8000
  copyright: © All rights reserved.
  locale: en
  keywords:
    - gatsby
    - blog
  twitter: '@n8tb1t'
  navMenuLinks: [
    { title: about, url: /about/ },
    { title: contacts, url: /contacts/ },
    { title: news, url: /blog/category/news/ },
    { title: tags, url: /blog/tags/ },
    { title: categories, url: /blog/category/ }
  ]

contentPaths:
  posts: content/blog
  pages: content/pages
  yaml: content/yaml

#  https://www.gatsbyjs.org/docs/path-prefix
pathPrefix: /custom-prefix

#  https://www.gatsbyjs.org/docs/asset-prefix/
assetPrefix: https://cdn.example.com

itemsPerPage:
  posts: 10
  categories: 1
  tags: 1
  authors: 1

templates:
  postsListByDate: ./src/templates/posts-list-by-date-template.jsx
  postsListByCategory: ./src/templates/posts-list-by-category-template.jsx
  postsListByTag: ./src/templates/posts-list-by-tag-template.jsx
  postsListByAuthor: ./src/templates/posts-list-by-author-template.jsx

slugs:
  tagPrefix: /blog/tag
  categoryPrefix: /blog/category
  authorPrefix: /blog/author

paging:
  blogPrefix: {root: /, pages: /blog/page}
  tagsPrefix: &taxonomy {root: '${ slug }', pages: '${ slug }page'}
  categoriesPrefix: *taxonomy
  authorsPrefix: {root: '${ slug }posts/', pages: '${ slug }posts/page'}
